version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - pg_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: evkosdev/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/backend-static/
      - media_value:/app/backend-media/ 
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: evkosdev/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend-static/
      - media_value:/var/html/backend-media/
    depends_on:
      - web
      - frontend
volumes:
  pg_value:
  static_value:
  media_value:
