# Generated by Django 3.2.16 on 2022-12-29 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(regex='^(#E26C2D|#49B64E|#8775D2)$')]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(regex='^(Завтрак|Обед|Ужин)$')]),
        ),
    ]
